### ISSUE TITLE
500 error(Internal server error) occurs after deploy

### ISSUE THREAD

**Issue by Ken0803** [piniajs/example-nuxt-3#50]
My website works fine on local computer.
But after deployment, it doesn't work.
It shows the 500 error and shows the "nuxtAppCtx.tryUse is not a function".
This is my package.json file.
It worked fine when nuxt version is "3.0.0-rc.5".(now I use "3.0.0-rc.8").

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "dependencies": {
    "@nuxtjs/tailwindcss": "^5.3.2",
    "@pinia/nuxt": "^0.4.0",
    "axios": "^0.27.2",
    "nuxt": "3.0.0-rc.8"
  }
}
```

**Comment by lazercaveman** [comment]
I am facing the same problem using nuxt-3 ... opened up a discussion on that a few days ago: https://github.com/vuejs/pinia/discussions/1619#discussioncomment-3538267

**Comment by posva** [comment]
Let's keep the discussion at https://github.com/vuejs/pinia/discussions/1619#discussioncomment-3538267 since this is jest an example repo
