### ISSUE TITLE
Something went wrong with this repository.

### ISSUE THREAD

**Issue by eMeRiKa13** [piniajs/example-nuxt-3#6]
Hi,

There is an error message in the preview https://stackblitz.com/github/piniajs/example-nuxt-3

and I can't make it works locally. Can you have a look, please?

Thanks

**Comment by posva** [comment]
It works locally. I opened https://github.com/stackblitz/core/issues/1656

**Comment by eMeRiKa13** [comment]
Thank you for your answer
